models:
  nsfw_detector:
    name: "AdamCodd/vit-base-nsfw-detector"
    context_window: null
  text_analyzer:
    name: "phi3"
    context_window: 8192
  code_analyzer:
    name: "phi3"
    context_window: 8192 
  image_describer:
    name: "llava:7b"
    context_window: 4096
  embedding_model:
    name: "nomic-embed-text"
    context_window: 2048
