# File Catalog Pipeline Configuration

# Maximum workers for each processing stage
max_workers:
  ingestion: 2
  validation: 2
  analysis: 0  # Disabled until Ollama is properly configured
  loading: 1

# File paths
paths:
  manifest: "data/manifest.json"
  database: "data/chromadb"